# Generated by Django 5.1.7 on 2026-04-08 16:24

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groupe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_groupe', models.CharField(max_length=120, unique=True)),
                ('filiere', models.CharField(max_length=120)),
                ('niveau', models.CharField(max_length=60)),
                ('annee_universitaire', models.CharField(max_length=20)),
                ('sujet_projet', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['nom_groupe'],
            },
        ),
        migrations.CreateModel(
            name='Materiel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=180, unique=True)),
                ('description', models.TextField(blank=True)),
                ('categorie', models.CharField(max_length=120)),
                ('quantite_totale', models.PositiveIntegerField(default=0)),
                ('quantite_disponible', models.PositiveIntegerField(default=0)),
                ('etat_general', models.CharField(choices=[('NEUF', 'Neuf'), ('BON', 'Bon'), ('PANNE', 'Panne'), ('MAINTENANCE', 'Maintenance')], default='BON', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='materials/')),
                ('date_achat', models.DateField(blank=True, null=True)),
                ('seuil_alerte', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('ETUDIANT', 'Etudiant'), ('ENSEIGNANT', 'Enseignant'), ('LABRESPO', 'LabRespo'), ('SERVICE_3PH', 'Service 3PH')], default='SERVICE_3PH', max_length=20)),
                ('departement', models.CharField(blank=True, max_length=120)),
                ('date_inscription', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Demande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_demande', models.CharField(choices=[('EXISTANT', 'Materiel existant'), ('NOUVEAU', 'Nouveau materiel')], max_length=10)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('COMMENTEE', 'Commentee enseignant'), ('VALIDEE', 'Validee'), ('REFUSEE', 'Refusee'), ('EN_COURS', 'Materiel sorti'), ('RETOURNEE', 'Retournee')], default='EN_ATTENTE', max_length=20)),
                ('date_demande', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_souhaitee_retour', models.DateField()),
                ('motif', models.TextField()),
                ('commentaire_enseignant', models.TextField(blank=True)),
                ('commentaire_labrespo', models.TextField(blank=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_etudiant', to=settings.AUTH_USER_MODEL)),
                ('groupe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demandes', to='lab.groupe')),
            ],
            options={
                'ordering': ['-date_demande'],
            },
        ),
        migrations.CreateModel(
            name='DemandeNouveauMateriel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_materiel_souhaite', models.CharField(max_length=180)),
                ('description', models.TextField()),
                ('categorie_souhaitee', models.CharField(max_length=120)),
                ('justification', models.TextField()),
                ('demande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nouveau_materiel', to='lab.demande')),
            ],
        ),
        migrations.CreateModel(
            name='AffectationGroupe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_affectation', models.DateTimeField(default=django.utils.timezone.now)),
                ('attribue_par', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations_creees', to=settings.AUTH_USER_MODEL)),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupes_assignes', to=settings.AUTH_USER_MODEL)),
                ('groupe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='affectation', to='lab.groupe')),
            ],
            options={
                'verbose_name': 'Affectation groupe',
                'verbose_name_plural': 'Affectations groupes',
                'ordering': ['-date_affectation'],
            },
        ),
        migrations.CreateModel(
            name='MouvementStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_mouvement', models.CharField(choices=[('SORTIE', 'Sortie'), ('RETOUR', 'Retour')], max_length=10)),
                ('quantite', models.PositiveIntegerField()),
                ('date_mouvement', models.DateTimeField(default=django.utils.timezone.now)),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements', to='lab.demande')),
                ('materiel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mouvements', to='lab.materiel')),
                ('valide_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mouvements_valides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_mouvement'],
            },
        ),
        migrations.CreateModel(
            name='LigneDemande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_demandee', models.PositiveIntegerField()),
                ('quantite_validee', models.PositiveIntegerField(default=0)),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes_demande', to='lab.demande')),
                ('materiel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes', to='lab.materiel')),
            ],
            options={
                'unique_together': {('demande', 'materiel')},
            },
        ),
        migrations.CreateModel(
            name='MembreGroupe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membreships', to=settings.AUTH_USER_MODEL)),
                ('groupe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membres', to='lab.groupe')),
            ],
            options={
                'verbose_name': 'Membre de groupe',
                'verbose_name_plural': 'Membres de groupes',
                'unique_together': {('etudiant', 'groupe')},
            },
        ),
    ]
