# Generated by Django 5.1.7 on 2026-04-09 08:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0002_demande_status_workflow'),
    ]

    operations = [
        migrations.CreateModel(
            name='Composant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=180)),
                ('reference', models.CharField(max_length=80, unique=True)),
                ('quantite_disponible', models.PositiveIntegerField(default=0)),
                ('seuil_alerte', models.PositiveIntegerField(default=0)),
                ('localisation', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'composants',
                'ordering': ['nom'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='classe',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='user',
            name='encadrant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etudiants_encadres', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ETUDIANT', 'Etudiant'), ('ENCADRANT', 'Encadrant'), ('ENSEIGNANT', 'Enseignant'), ('LABO_TEMPS', 'Labo Temps'), ('LABRESPO', 'LabRespo'), ('SERVICE_ACHAT', 'Service Achat'), ('SERVICE_3PH', 'Service 3PH')], default='SERVICE_3PH', max_length=20),
        ),
        migrations.CreateModel(
            name='DemandeWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField()),
                ('statut', models.CharField(choices=[('en_attente_encadrant', 'En attente encadrant'), ('en_attente_labo', 'En attente labo'), ('en_attente_achat', 'En attente achat'), ('approuvee', 'Approuvee'), ('refusee', 'Refusee'), ('terminee', 'Terminee')], default='en_attente_encadrant', max_length=30)),
                ('date_demande', models.DateTimeField(default=django.utils.timezone.now)),
                ('commentaire_encadrant', models.TextField(blank=True)),
                ('date_derniere_maj', models.DateTimeField(auto_now=True)),
                ('composant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demandes', to='lab.composant')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_demandes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'demandes',
                'ordering': ['-date_demande'],
            },
        ),
        migrations.CreateModel(
            name='Achat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_achetee', models.PositiveIntegerField()),
                ('fournisseur', models.CharField(max_length=180)),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('recu', 'Recu')], default='en_cours', max_length=20)),
                ('date_commande', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_reception', models.DateTimeField(blank=True, null=True)),
                ('composant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='achats', to='lab.composant')),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achats', to='lab.demandeworkflow')),
            ],
            options={
                'db_table': 'achats',
                'ordering': ['-date_commande'],
            },
        ),
        migrations.CreateModel(
            name='HistoriqueAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('date_action', models.DateTimeField(default=django.utils.timezone.now)),
                ('acteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historique_actions', to=settings.AUTH_USER_MODEL)),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_actions', to='lab.demandeworkflow')),
            ],
            options={
                'db_table': 'historique',
                'ordering': ['-date_action'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
