# Generated by Django 5.1.7 on 2026-04-09 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0004_remove_labo_temps_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE_VALIDATION_ENSEIGNANT', 'En attente de validation enseignant'), ('VALIDEE_PAR_ENSEIGNANT', 'Validee par enseignant'), ('EN_COURS_TRAITEMENT', 'En cours de traitement'), ('EN_PAUSE', 'En pause'), ('ENVOYEE_SERVICE_ACHAT', 'Envoyee au service achat'), ('ACHAT_EN_COURS_TRAITEMENT', 'Achat en cours de traitement'), ('ACHAT_EN_COURS_LIVRAISON', 'Achat en cours de livraison'), ('MATERIEL_RECU_AU_LABO', 'Materiel recu au laboratoire'), ('DISPONIBLE', 'Disponible'), ('REFUSEE', 'Refusee'), ('RETIREE', 'Retiree'), ('TERMINEE', 'Terminee')], default='EN_ATTENTE_VALIDATION_ENSEIGNANT', max_length=40),
        ),
    ]
