# Generated by Django 5.1.7 on 2026-04-13 19:48

from django.db import migrations, models


def migrate_enseignant_to_encadrant(apps, schema_editor):
    User = apps.get_model("lab", "User")
    User.objects.filter(role="ENSEIGNANT").update(role="ENCADRANT")


def migrate_encadrant_to_enseignant(apps, schema_editor):
    User = apps.get_model("lab", "User")
    User.objects.filter(role="ENCADRANT").update(role="ENSEIGNANT")


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0005_alter_demande_statut'),
    ]

    operations = [
        migrations.RunPython(
            migrate_enseignant_to_encadrant,
            migrate_encadrant_to_enseignant,
        ),
        migrations.AlterField(
            model_name='demande',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE_VALIDATION_ENSEIGNANT', 'En attente de validation encadrant'), ('VALIDEE_PAR_ENSEIGNANT', 'Validee par encadrant'), ('EN_COURS_TRAITEMENT', 'En cours de traitement'), ('EN_PAUSE', 'En pause'), ('ENVOYEE_SERVICE_ACHAT', 'Envoyee au service achat'), ('ACHAT_EN_COURS_TRAITEMENT', 'Achat en cours de traitement'), ('ACHAT_EN_COURS_LIVRAISON', 'Achat en cours de livraison'), ('MATERIEL_RECU_AU_LABO', 'Materiel recu au laboratoire'), ('DISPONIBLE', 'Disponible'), ('REFUSEE', 'Refusee'), ('RETIREE', 'Retiree'), ('TERMINEE', 'Terminee')], default='EN_ATTENTE_VALIDATION_ENSEIGNANT', max_length=40),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ETUDIANT', 'Etudiant'), ('ENCADRANT', 'Encadrant'), ('LABRESPO', 'LabRespo'), ('SERVICE_ACHAT', 'Service Achat'), ('SERVICE_3PH', 'Service 3PH')], default='SERVICE_3PH', max_length=20),
        ),
    ]
