# Generated by Django 5.1.7 on 2026-04-13 20:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def forward_copy_primary_encadrant_to_many(apps, schema_editor):
    User = apps.get_model("lab", "User")
    for etudiant in User.objects.exclude(encadrant_id=None):
        etudiant.encadrants.add(etudiant.encadrant_id)


def backward_copy_many_to_primary_encadrant(apps, schema_editor):
    User = apps.get_model("lab", "User")
    for etudiant in User.objects.all():
        first = etudiant.encadrants.first()
        etudiant.encadrant_id = first.id if first else None
        etudiant.save(update_fields=["encadrant"])


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0006_alter_demande_statut_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='encadrants',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'ENCADRANT'}, related_name='etudiants_multi', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='encadrant',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'ENCADRANT'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etudiants_encadres', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(
            forward_copy_primary_encadrant_to_many,
            backward_copy_many_to_primary_encadrant,
        ),
    ]
