from django.urls import path

from .views import (
    AchatCreateAPIView,
    AchatDemandesAttenteAPIView,
    AchatReceptionnerAPIView,
    ComposantListCreateAPIView,
    ComposantUpdateAPIView,
    EncadrantAdminDetailAPIView,
    EncadrantAdminListCreateAPIView,
    EncadrantDemandesClasseAPIView,
    EncadrantRefuserAPIView,
    EncadrantValiderAPIView,
    LaboDemandesAttenteAPIView,
    LaboReserverAPIView,
    LoginAPIView,
    LogoutAPIView,
    MeAPIView,
    NotificationReadAPIView,
    NotificationsAPIView,
    RapportsAPIView,
    StatistiquesAPIView,
    StudentAdminDetailAPIView,
    StudentAdminListCreateAPIView,
    StudentDemandeCreateAPIView,
    StudentDemandeDeleteAPIView,
    StudentMesDemandesAPIView,
)

urlpatterns = [
    path("login", LoginAPIView.as_view(), name="api_login"),
    path("logout", LogoutAPIView.as_view(), name="api_logout"),
    path("me", MeAPIView.as_view(), name="api_me"),
    path("notifications", NotificationsAPIView.as_view(), name="api_notifications"),
    path(
        "notifications/<int:notification_id>/read",
        NotificationReadAPIView.as_view(),
        name="api_notification_read",
    ),
    path("composants", ComposantListCreateAPIView.as_view(), name="api_composants"),
    path(
        "composants/<int:composant_id>",
        ComposantUpdateAPIView.as_view(),
        name="api_composant_update",
    ),
    path("demandes", StudentDemandeCreateAPIView.as_view(), name="api_demande_create"),
    path("mes-demandes", StudentMesDemandesAPIView.as_view(), name="api_mes_demandes"),
    path("demande/<int:demande_id>", StudentDemandeDeleteAPIView.as_view(), name="api_demande_delete"),
    path("demandes/classe", EncadrantDemandesClasseAPIView.as_view(), name="api_demandes_classe"),
    path(
        "demande/<int:demande_id>/valider-encadrant",
        EncadrantValiderAPIView.as_view(),
        name="api_demande_valider_encadrant",
    ),
    path(
        "demande/<int:demande_id>/refuser-encadrant",
        EncadrantRefuserAPIView.as_view(),
        name="api_demande_refuser_encadrant",
    ),
    path("demandes/attente-labo", LaboDemandesAttenteAPIView.as_view(), name="api_attente_labo"),
    path(
        "demande/<int:demande_id>/reserver",
        LaboReserverAPIView.as_view(),
        name="api_demande_reserver",
    ),
    path("demandes/attente-achat", AchatDemandesAttenteAPIView.as_view(), name="api_attente_achat"),
    path("achats", AchatCreateAPIView.as_view(), name="api_achats_create"),
    path(
        "achats/<int:achat_id>/receptionner",
        AchatReceptionnerAPIView.as_view(),
        name="api_achat_receptionner",
    ),
    path("encadrants", EncadrantAdminListCreateAPIView.as_view(), name="api_encadrants"),
    path(
        "encadrants/<int:encadrant_id>",
        EncadrantAdminDetailAPIView.as_view(),
        name="api_encadrant_detail",
    ),
    path("etudiants", StudentAdminListCreateAPIView.as_view(), name="api_etudiants"),
    path(
        "etudiants/<int:student_id>",
        StudentAdminDetailAPIView.as_view(),
        name="api_etudiant_detail",
    ),
    path("statistiques", StatistiquesAPIView.as_view(), name="api_statistiques"),
    path("rapports", RapportsAPIView.as_view(), name="api_rapports"),
]
